# https://taskfile.dev/

version: 3

tasks:
  default:
    cmds:
      - task -l
    silent: true

  run:
    desc: Runs the app.
    cmds:
      - go run main.go
  
  cdb:start:
    desc: Starts CockroachDB.
    cmds:
      - cockroach start-single-node --insecure
