version: "3.7"

services:
  app:
    # the "app" service is for VS-Code's devcontainer,
    # which is also the home for our Go app's code
    image: mcr.microsoft.com/devcontainers/go:0-1.19
    container_name: app
    user: vscode
    env_file:
      # First, load default environment variables.
      - .env.default
      # Next, if you have a .devcontainer/.env file, then it will be loaded,
      # allowing overwriting of the defaults. Else, the placeholder file
      # .devcontainer/.env.DEMO will be loaded, which changes no settings.
      - ${ENV_FILE:-.env.DEMO}
    command: sleep infinity
    volumes:
      - ..:/workspace

  cockroachdb:
    image: cockroachdb/cockroach:latest-v22.2
    container_name: cockroachdb
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroachdb/cockroach-data:/cockroach/cockroach-data"
    ports:
      - 26257:26257
      - 8080:8080

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "${PWD}/elasticsearch/data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
